STRINGS.SKILLTREE.FRISIA = {
    SKILLUP_I_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SKILLUP_I_DESC,
    SKILLUP_I_TITLE = TUNING.SOULTIDE.LANGUAGE.FRISIA_SKILLUP_I_TITLE,

    SKILLUP_II_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SKILLUP_II_DESC,
    SKILLUP_II_TITLE = TUNING.SOULTIDE.LANGUAGE.FRISIA_SKILLUP_II_TITLE,

    SKILLUP_III_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SKILLUP_III_DESC,
    SKILLUP_III_TITLE = TUNING.SOULTIDE.LANGUAGE.FRISIA_SKILLUP_III_TITLE,

    SKILLUP_IV_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SKILLUP_IV_DESC,
    SKILLUP_IV_TITLE = TUNING.SOULTIDE.LANGUAGE.FRISIA_SKILLUP_IV_TITLE,

    SOULCORE_I_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_I_DESC,
    SOULCORE_I_TITLE = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_I_TITLE,

    SOULCORE_II_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_II_DESC,
    SOULCORE_II_TITLE = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_II_TITLE,

    SOULCORE_III_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_III_DESC,
    SOULCORE_III_TITLE = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_III_TITLE,

    SOULCORE_IV_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_IV_DESC,
    SOULCORE_IV_TITLE = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_IV_TITLE,

    SOULCORE_V_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_V_DESC,
    SOULCORE_V_TITLE = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_V_TITLE,

    SOULCORE_POTENTIAL_I_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_POTENTIAL_I_DESC,
    SOULCORE_POTENTIAL_I_TITLE = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_POTENTIAL_I_TITLE,

    SOULCORE_POTENTIAL_II_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_POTENTIAL_II_DESC,
    SOULCORE_POTENTIAL_II_TITLE = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_POTENTIAL_II_TITLE,

    SOULCORE_POTENTIAL_III_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_POTENTIAL_III_DESC,
    SOULCORE_POTENTIAL_III_TITLE = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_POTENTIAL_III_TITLE,

    SOULCORE_POTENTIAL_IV_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_POTENTIAL_IV_DESC,
    SOULCORE_POTENTIAL_IV_TITLE = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_POTENTIAL_IV_TITLE,

    SOULCORE_POTENTIAL_V_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_POTENTIAL_V_DESC,
    SOULCORE_POTENTIAL_V_TITLE = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_POTENTIAL_V_TITLE,

    LIVE_WORKEFFI_I_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_LIVE_WORKEFFI_I_DESC,
    LIVE_WORKEFFI_I_TITLE = TUNING.SOULTIDE.LANGUAGE.FRISIA_LIVE_WORKEFFI_I_TITLE,

    LIVE_WORKEFFI_II_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_LIVE_WORKEFFI_II_DESC,
    LIVE_WORKEFFI_II_TITLE = TUNING.SOULTIDE.LANGUAGE.FRISIA_LIVE_WORKEFFI_II_TITLE,

    SOULTIDE_SP_I_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULTIDE_SP_I_DESC,
    SOULTIDE_SP_I_TITLE =TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULTIDE_SP_I_TITLE,

    SOULTIDE_SP_II_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULTIDE_SP_II_DESC,
    SOULTIDE_SP_II_TITLE =TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULTIDE_SP_II_TITLE,

    SOULTIDE_SP_III_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULTIDE_SP_III_DESC,
    SOULTIDE_SP_III_TITLE =TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULTIDE_SP_III_TITLE,

    EXCEED_I_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_EXCEED_I_DESC ,
    EXCEED_I_TITLE = TUNING.SOULTIDE.LANGUAGE.FRISIA_EXCEED_I_TITLE ,

    EXCEED_II_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_EXCEED_I_DESC ,
    EXCEED_II_TITLE = TUNING.SOULTIDE.LANGUAGE.FRISIA_EXCEED_I_TITLE ,

    ---------locks
    SCALE_LOCK_I_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SCALE_LOCK_I_DESC,
    SCALE_LOCK_II_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SCALE_LOCK_II_DESC,
    SCALE_LOCK_III_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SCALE_LOCK_III_DESC,
    SCALE_LOCK_IV_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SCALE_LOCK_IV_DESC,
    SCALE_LOCK_V_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SCALE_LOCK_V_DESC,
    SCALE_LOCK_VI_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SCALE_LOCK_VI_DESC,

    SOULCORE_LOCK_I_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_LOCK_I_DESC ,
    SOULCORE_LOCK_II_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_LOCK_II_DESC ,
    SOULCORE_LOCK_III_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_LOCK_III_DESC ,
    SOULCORE_LOCK_IV_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_LOCK_IV_DESC ,
    SOULCORE_LOCK_V_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_LOCK_V_DESC ,

    SOULCOR_POTENTIAL_LOCK_I_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_POTENTIAL_LOCK_I_DESC ,
    SOULCOR_POTENTIAL_LOCK_II_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_POTENTIAL_LOCK_II_DESC ,
    SOULCOR_POTENTIAL_LOCK_III_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_POTENTIAL_LOCK_III_DESC ,
    SOULCOR_POTENTIAL_LOCK_IV_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_POTENTIAL_LOCK_IV_DESC ,
    SOULCOR_POTENTIAL_LOCK_V_DESC = TUNING.SOULTIDE.LANGUAGE.FRISIA_SOULCORE_POTENTIAL_LOCK_V_DESC ,
}
