--制作栏
STRINGS.UI.CRAFTING_FILTERS.SOULTIDE = TUNING.SOULTIDE.LANGUAGE.CRAFTING_FILTERS_SOULTIDE
STRINGS.UI.CRAFTING_FILTERS.SOUL_CANDY =TUNING.SOULTIDE.LANGUAGE.CRAFTING_FILTERS_SOUL_CANDY
STRINGS.UI.CRAFTING.NEEDSSOULTIDE_SCIENCE = "需要建造一个水晶塔来解锁"
STRINGS.ACTIONS.OPEN_CRAFTING.CRYSTAL = TUNING.SOULTIDE.LANGUAGE.OPEN_CRAFTING_CRYSTAL

--一些配方
STRINGS.RECIPE_DESC.SOULTIDE_GREENCANDY_B = " 一次10个，8折优惠！"
STRINGS.RECIPE_DESC.SOULTIDE_MOONSOUL_BLUE_B = " 一次10个，8折优惠！"
STRINGS.RECIPE_DESC.SOULTIDE_CANDYBAG_BLUE_B = " 一次10个，8折优惠！"
--武器

--人物描述
-- The character select screen lines  --人物选人界面的描述
STRINGS.CHARACTER_TITLES.frisia = "芙丽希娅frisia"
STRINGS.CHARACTER_NAMES.frisia = "Frisia"
STRINGS.CHARACTER_DESCRIPTIONS.frisia = TUNING.SOULTIDE.LANGUAGE.CHARACTER_DESCRIPTIONS_FRISIA
STRINGS.CHARACTER_QUOTES.frisia = TUNING.SOULTIDE.LANGUAGE.CHARACTER_QUOTES_FRISIA
STRINGS.CHARACTER_SURVIVABILITY.frisia= TUNING.SOULTIDE.LANGUAGE.CHARACTER_SURVIVABILITY_FRISIA

-- Custom speech strings  ----人物语言文件  可以进去自定义
STRINGS.CHARACTERS.FRISIA = require "speech_winona"

-- The character's name as appears in-game  --人物在游戏里面的名字
STRINGS.NAMES.FRISIA = "Frisia"
STRINGS.SKIN_NAMES.frisia_none = "Frisia"  --检查界面显示的名字