--制作栏
STRINGS.UI.CRAFTING_FILTERS.SOULTIDE ="灵魂潮汐-基础"
--一些配方
STRINGS.RECIPE_DESC.SOULTIDE_GREENCANDY_B = " 一次10个，8折优惠！"
STRINGS.RECIPE_DESC.SOULTIDE_MOONSOUL_BLUE_B = " 一次10个，8折优惠！"
--武器
STRINGS.NAMES.SOULTIDE_DGS = "绝园之镰"
STRINGS.RECIPE_DESC.SOULTIDE_DGS = "某人最喜欢的花园打理工具"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SOULTIDE_DGS = "上面沾满了怨气。。"